# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import djcelery.picklefield
import errorlog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.BooleanField(default=False)),
                ('occur_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fix_time', models.DateTimeField(null=True)),
                ('error_type', models.TextField()),
                ('error_args_json', models.TextField(null=True)),
                ('stack_list_json', models.TextField(null=True)),
                ('stack_hash', models.TextField(db_index=True)),
                ('error_html', models.TextField(null=True)),
                ('vcs_rev', models.TextField(default=errorlog.models.get_vcs_rev, null=True)),
                ('args', djcelery.picklefield.PickledObjectField(editable=False)),
                ('kwargs', djcelery.picklefield.PickledObjectField(editable=False)),
                ('args_repr', models.TextField(blank=True, null=True)),
                ('kwargs_repr', models.TextField(blank=True, null=True)),
                ('task_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occur_time'],
                'abstract': False,
            },
        ),
    ]
